Connection_Params:
  Device_ID: dev7811
  Device_IP: 192.168.1.101
  RF_IP: 192.168.1.102
LIA_Params:
  Burst_Dur: '0.005'
  Duration: '10'
  FFT_50_Ohm: 'False'
  FFT_AC_Coupling: 'False'
  FFT_Average: '10'
  FFT_Duration: '5'
  FFT_Sample_Rate: '1'
  Filter_Order: '7'
  Range: '0'
  Sample_Rate: '50'
  Scaling: '750'
  Time_Const: '600'
RF_Params:
  A_Matrix_Values:
  - - 1
    - 1
    - 1
  - - 1
    - 1
    - 1
  - - 1
    - 1
    - 1
  - - 1
    - 1
    - 1
  Ext_Mod: 'False'
  Feedback_Freq_Table:
  - - 2.71
    - 2.72
    - 2.73
    - 2.74
  - - 0.1
    - 0.1
    - 0.1
    - 0.1
  Freq: '2.75'
  Mod_Amp: '2.8'
  Mod_Freq: '3.05'
  Mod_On: 'True'
  Mod_Type: '1'
  Power: '-30.0'
  Power_On: 'True'
Stage_Params:
  Avg_Time: '0.1'
  Dwell: '0.05'
  X_End: '20.0'
  X_Start: '10.0'
  X_Step: '1.0'
  Y_End: '20.0'
  Y_Start: '10.0'
  Y_Step: '1.0'
Sweep_Params:
  Dwell: '3.0'
  Points: '1000'
  Sweep_End: '3.0'
  Sweep_Start: '2.7'
  Sweep_Step: '250.0'
  Sweep_Type: '1'
